trafgen: Fix for ipv6 header generation when L3-only devices are present
netsniff-ng/netsniff-ng pull request #233
Opened 2022-04-15 16:51 UTC by MatPerin

When trying to run trafgen with a config which included the ipv6() header generation helper function, I noticed the tool halting without sending any traffic.

By further inspection I found out that the issue was a segmentation fault caused by NULL pointer deferencing inside the lookup function for the device ipv6 address.
Apparently, the getifaddrs function returns a linked list node for L2 even in the case of L3 interfaces (in my case, it was a TUN device created in the network) but with the pointer to the address structure set to NULL. This causes a segfault when trying to access the address family from it.
I solved the issue by checking the validity of the pointer beforehand.

2022-04-21 19:00 UTC, tklauser requested changes
Thanks for the contribution @MatPerin!

One small nit inline. Also, could you please add the change description to the commit message as well and add a `Signed-off-by` line as outlined in [`SubmittingPatches`](https://github.com/netsniff-ng/netsniff-ng/blob/master/SubmittingPatches)?

2022-04-21 19:00 UTC, tklauser commented on dev.c
> +		if(ifa->ifa_addr == NULL)
Nit: please add a space between `if` and opening parenthesis

```suggestion
		if (ifa->ifa_addr == NULL)
```

2022-04-22 09:10 UTC, MatPerin commented
Sure, sorry for not including the commit message and the `signed-off-by` label.
It should be all fixed now, let me know if further changes are needed.

2022-04-22 09:17 UTC, tklauser approved these changes
Thank you @MatPerin, looks perfect now!

2022-04-22 09:20 UTC, merged